# 1. Obtendo dados cadastrais das empresas de capital aberto

In [1]:
import pandas as pd
import numpy as np
import requests

In [2]:
link = 'http://dados.cvm.gov.br/dados/CIA_ABERTA/CAD/DADOS/cad_cia_aberta.csv'

In [3]:
r = requests.get(link)

In [4]:
linhas = []

for i in r.text.split('\n'):
    linhas.append(i.strip().split(';'))

In [5]:
data = pd.DataFrame(linhas[1:], columns = linhas[0])

In [6]:
data.head()

,CNPJ_CIA,DENOM_SOCIAL,DENOM_COMERC,DT_REG,DT_CONST,DT_CANCEL,MOTIVO_CANCEL,SIT,DT_INI_SIT,CD_CVM,...,UF_RESP,PAIS_RESP,CEP_RESP,DDD_TEL_RESP,TEL_RESP,DDD_FAX_RESP,FAX_RESP,EMAIL_RESP,CNPJ_AUDITOR,AUDITOR
0,08.773.135/0001-00,2W ECOBANK S.A.,2W ECOBANK S.A.,2020-10-29,2007-03-23,,,ATIVO,2020-10-29,25224,...,SP,,4707000,11,39579400,,,ri@2wecobank.com.br,52.803.244/0001-06,KPMG AUDITORES ASSOCIADOS
1,11.396.633/0001-87,3A COMPANHIA SECURITIZADORA,TRIPLO A COMPANHIA SECURITIZADORA,2010-03-08,2009-11-03,2015-12-18,Cancelamento Voluntário - IN CVM 480/09,CANCELADA,2015-12-18,21954,...,RJ,,20020000,21,22338867,21,22338867,juridico@triploasec.com.br,60.525.706/0001-07,MOORE STEPHENS LIMA LUCCHESI AUDITORES INDEPEN...
2,12.091.809/0001-55,3R PETROLEUM OLÉO E GÁS S.A.,,2020-11-09,2010-06-08,,,ATIVO,2020-11-09,25291,...,RJ,,22250145,21,34755555,,,ri@3rpetroleum.com.br,57.755.217/0001-29,KPMG AUDITORES INDEPENDENTES LTDA.
3,01.547.749/0001-16,521 PARTICIPAÇOES S.A. - EM LIQUIDAÇĂO EXTRAJU...,521 PARTICIPAÇŐES S/A,1997-07-11,1996-07-30,,,ATIVO,1997-07-11,16330,...,,,,,,,,,13.859.935/0001-70,BAKER TILLY BRASIL RJ AUDITORES INDEPENDENTES ...
4,01.851.771/0001-55,524 PARTICIPAÇOES SA,524 PARTICIPACOES SA,1997-05-30,1997-04-02,,,ATIVO,1997-05-30,16284,...,RJ,,20020010,21,38043700,,,gar@opportunity.com.br,40.262.602/0001-31,"BKR - LOPES, MACHADO AUDITORES"

In [7]:
#Usando list comprehision
lines = [i.strip().split(';') for i in r.text.split('\n')]

In [8]:
data = pd.DataFrame(lines[1:], columns = lines[0])

In [9]:
data.head()

,CNPJ_CIA,DENOM_SOCIAL,DENOM_COMERC,DT_REG,DT_CONST,DT_CANCEL,MOTIVO_CANCEL,SIT,DT_INI_SIT,CD_CVM,...,UF_RESP,PAIS_RESP,CEP_RESP,DDD_TEL_RESP,TEL_RESP,DDD_FAX_RESP,FAX_RESP,EMAIL_RESP,CNPJ_AUDITOR,AUDITOR
0,08.773.135/0001-00,2W ECOBANK S.A.,2W ECOBANK S.A.,2020-10-29,2007-03-23,,,ATIVO,2020-10-29,25224,...,SP,,4707000,11,39579400,,,ri@2wecobank.com.br,52.803.244/0001-06,KPMG AUDITORES ASSOCIADOS
1,11.396.633/0001-87,3A COMPANHIA SECURITIZADORA,TRIPLO A COMPANHIA SECURITIZADORA,2010-03-08,2009-11-03,2015-12-18,Cancelamento Voluntário - IN CVM 480/09,CANCELADA,2015-12-18,21954,...,RJ,,20020000,21,22338867,21,22338867,juridico@triploasec.com.br,60.525.706/0001-07,MOORE STEPHENS LIMA LUCCHESI AUDITORES INDEPEN...
2,12.091.809/0001-55,3R PETROLEUM OLÉO E GÁS S.A.,,2020-11-09,2010-06-08,,,ATIVO,2020-11-09,25291,...,RJ,,22250145,21,34755555,,,ri@3rpetroleum.com.br,57.755.217/0001-29,KPMG AUDITORES INDEPENDENTES LTDA.
3,01.547.749/0001-16,521 PARTICIPAÇOES S.A. - EM LIQUIDAÇĂO EXTRAJU...,521 PARTICIPAÇŐES S/A,1997-07-11,1996-07-30,,,ATIVO,1997-07-11,16330,...,,,,,,,,,13.859.935/0001-70,BAKER TILLY BRASIL RJ AUDITORES INDEPENDENTES ...
4,01.851.771/0001-55,524 PARTICIPAÇOES SA,524 PARTICIPACOES SA,1997-05-30,1997-04-02,,,ATIVO,1997-05-30,16284,...,RJ,,20020010,21,38043700,,,gar@opportunity.com.br,40.262.602/0001-31,"BKR - LOPES, MACHADO AUDITORES"

Filtrando empresas de um setor específico

In [10]:
#Filtrando por shopping
searchfor = ['MULTIPLAN', 'MALL', 'IGUATEMI', 'SHOPP']
shoppings = data[data.DENOM_SOCIAL.str.contains('|'.join(searchfor), na = False)]

In [11]:
shoppings.head()

,CNPJ_CIA,DENOM_SOCIAL,DENOM_COMERC,DT_REG,DT_CONST,DT_CANCEL,MOTIVO_CANCEL,SIT,DT_INI_SIT,CD_CVM,...,UF_RESP,PAIS_RESP,CEP_RESP,DDD_TEL_RESP,TEL_RESP,DDD_FAX_RESP,FAX_RESP,EMAIL_RESP,CNPJ_AUDITOR,AUDITOR
72,06.082.980/0001-03,ALIANSCE SHOPPING CENTERS S/A,ALIANSCE,2008-01-18,2004-01-01,2019-08-05,ELISĂO POR INCORPORAÇĂO,CANCELADA,2019-08-05,21300,...,RJ,,22431050,21,21767272,21,21767229,ri@aliansce.com.br,61.562.112/0001-20,PRICEWATERHOUSECOOPERS AUDITORES INDEPENDENTES...
85,82.120.676/0001-83,ALMEIDA JUNIOR SHOPPING CENTERS S.A.,ALMEIDA JUNIOR SHOPPING CENTERS S.A.,2021-11-22,1990-08-01,,,ATIVO,2021-11-22,26395,...,,,1452000,11,37073333,,,ri@almeidajunior.com.br,61.366.936/0001-25,ERNST & YOUNG AUDITORES INDEPENDENTES S/S LTDA.
123,00.979.769/0001-01,ANCAR SHOPPING SA,ANCAR,1996-01-11,1995-12-01,2001-11-30,ELISĂO POR INCORPORAÇĂO,CANCELADA,2001-11-30,15326,...,RJ,,20011020,21,38062700,21,38062749,ancar@ancar.com.br,33.017.310/0001-78,RUHTRA S/C
388,06.977.745/0001-91,BR MALLS PARTICIPAÇOES S.A.,BR MALLS PARTICIPAÇOES S.A.,2006-01-04,2004-05-26,,,ATIVO,2006-01-04,19909,...,,,22430041,21,31389901,,,al-ri@alianscesonae.com.br,49.928.567/0001-11,DELOITTE TOUCHE TOHMATSU AUDITORES INDEPENDENT...
986,00.664.949/0001-96,DIAMONDMALL SA EMPREENDS PARTS,DIAMONDMALL SA,1995-09-27,,1997-01-10,ATENDIMENTO AS NORMAS DA INSTR CVM 03/78,CANCELADA,1997-01-10,15059,...,RJ,,20036900,21,2974141,0021,2201780,,33.017.310/0001-78,RUHTRA S/C

Filtro por CNPJ

In [12]:
lista_cnpjs = ['05.878.397/0001-32','08.294.224/0001-65', '07.816.890/0001-53', '51.218.147/0001-93', '06.977.751/0001-49']

In [13]:
jhsf = '08.294.224/0001-65'

In [14]:
jhsf_data = data[data['CNPJ_CIA']== jhsf]

In [15]:
jhsf_data

,CNPJ_CIA,DENOM_SOCIAL,DENOM_COMERC,DT_REG,DT_CONST,DT_CANCEL,MOTIVO_CANCEL,SIT,DT_INI_SIT,CD_CVM,...,UF_RESP,PAIS_RESP,CEP_RESP,DDD_TEL_RESP,TEL_RESP,DDD_FAX_RESP,FAX_RESP,EMAIL_RESP,CNPJ_AUDITOR,AUDITOR
1501,08.294.224/0001-65,JHSF PARTICIPAÇŐES SA,JHSF,2007-04-04,2006-06-29,,,ATIVO,2007-04-04,20605,...,SP,,5502001,11,37025473,,,ri@jhsf.com.br,61.366.936/0001-25,ERNST & YOUNG AUDITORES INDEPENDENTES S/S LTDA.

In [16]:
filtrados = data[data['CNPJ_CIA'].isin(lista_cnpjs)]

In [17]:
filtrados

,CNPJ_CIA,DENOM_SOCIAL,DENOM_COMERC,DT_REG,DT_CONST,DT_CANCEL,MOTIVO_CANCEL,SIT,DT_INI_SIT,CD_CVM,...,UF_RESP,PAIS_RESP,CEP_RESP,DDD_TEL_RESP,TEL_RESP,DDD_FAX_RESP,FAX_RESP,EMAIL_RESP,CNPJ_AUDITOR,AUDITOR
80,05.878.397/0001-32,ALLOS S.A.,ALLOS S.A.,2011-02-01,2003-07-17,,,ATIVO,2011-02-01,22357,...,RJ,,22430060,21,25839800,,,ri@allos.co,49.928.567/0001-11,DELOITTE TOUCHE TOHMATSU AUDITORES INDEPENDENT...
81,05.878.397/0001-32,ALLOS S.A.,ALLOS S.A.,2011-02-01,2003-07-17,,,ATIVO,2011-02-01,22357,...,RJ,,22430060,21,25839800,,,ri@allos.co,49.928.567/0001-11,DELOITTE TOUCHE TOHMATSU AUDITORES INDEPENDENT...
389,06.977.751/0001-49,BR PROPERTIES S.A.,BR PROPERTIES S.A.,2006-01-04,2004-05-26,2023-12-20,Cancelamento Voluntário - IN CVM 480/09,CANCELADA,2023-12-20,19925,...,SP,,4578000,011,32011000,011,32011001,ri@brpr.com.br,57.755.217/0001-29,KPMG AUDITORES INDEPENDENTES LTDA.
390,06.977.751/0001-49,BR PROPERTIES S.A.,BR PROPERTIES S.A.,2006-01-04,2004-05-26,2023-12-20,Cancelamento Voluntário - IN CVM 480/09,CANCELADA,2023-12-20,19925,...,SP,,4578000,011,32011000,011,32011001,ri@brpr.com.br,57.755.217/0001-29,KPMG AUDITORES INDEPENDENTES LTDA.
1361,51.218.147/0001-93,IGUATEMI EMPRESA DE SHOPPING CENTERS S/A,IGUATEMI EMPRESA DE SHOPPING CENTERS S/A,2007-02-02,1979-05-23,,,ATIVO,2007-02-02,20494,...,SP,,1455070,11,31377037,0,0,ri@iguatemi.com.br,49.928.567/0001-11,DELOITTE TOUCHE TOHMATSU AUDITORES INDEPENDENT...
1501,08.294.224/0001-65,JHSF PARTICIPAÇŐES SA,JHSF,2007-04-04,2006-06-29,,,ATIVO,2007-04-04,20605,...,SP,,5502001,11,37025473,,,ri@jhsf.com.br,61.366.936/0001-25,ERNST & YOUNG AUDITORES INDEPENDENTES S/S LTDA.
1770,07.816.890/0001-53,MULTIPLAN - EMPREEND IMOBILIARIOS S.A.,MULTIPLAN,2007-07-25,2005-12-30,,,ATIVO,2007-07-25,20982,...,RJ,,22640102,21,30315224,21,30315322,ri@multiplan.com.br,57.755.217/0001-29,KPMG AUDITORES INDEPENDENTES LTDA.
1771,07.816.890/0001-53,MULTIPLAN - EMPREEND IMOBILIARIOS S.A.,MULTIPLAN,2007-07-25,2005-12-30,,,ATIVO,2007-07-25,20982,...,RJ,,22640102,21,30315224,21,30315322,ri@multiplan.com.br,57.755.217/0001-29,KPMG AUDITORES INDEPENDENTES LTDA.

In [18]:
empresas = list(filtrados['CD_CVM'])

In [19]:
empresas

['22357', '22357', '19925', '19925', '20494', '20605', '20982', '20982']

# 2. Extração dos demonstrativos trimestrais das empresas

In [20]:
import zipfile
import io
import xlsxwriter

Quais demonstrativos você precisa?

Em 'arquivo', determine o tipo de demonstrativo e o ano

Esse 'arquivo' precisa estar contido na pasta zipada da CVM

O 'arquivo' precisa estar na pasta zipada contida em 'link'

In [21]:
arquivo = 'itr_cia_aberta_DRE_con_2021.csv'
link = 'http://dados.cvm.gov.br/dados/CIA_ABERTA/DOC/ITR/DADOS/itr_cia_aberta_2021.zip'

In [22]:
arquivo_zip = requests.get(link)

KeyboardInterrupt:

In [ ]:
zf = zipfile.ZipFile(io.BytesIO(arquivo_zip.content))

In [ ]:
zf

In [ ]:
DRE = zf.open(arquivo)

In [ ]:
linhas = DRE.readlines()

In [ ]:
lines = [i.strip().decode('ISO-8859-1') for i in linhas]

In [ ]:
lines = [i.split(';') for i in lines]

In [ ]:
df = pd.DataFrame(lines[1:], columns = lines[0])

In [ ]:
df.head(3)

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
0,00.001.180/0001-26,2021-03-31,2,CENTRAIS ELET BRAS S.A. - ELETROBRAS,002437,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-03-31,3.01,Receita de Venda de Bens e/ou Serviços,7603566.0000000000,S
1,00.001.180/0001-26,2021-03-31,2,CENTRAIS ELET BRAS S.A. - ELETROBRAS,002437,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-03-31,3.01,Receita de Venda de Bens e/ou Serviços,8208426.0000000000,S
2,00.001.180/0001-26,2021-03-31,2,CENTRAIS ELET BRAS S.A. - ELETROBRAS,002437,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-03-31,3.02,Custo dos Bens e/ou Serviços Vendidos,-3042280.0000000000,S

In [ ]:
df[df['CD_CVM'] == '019909']

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
28846,06.977.745/0001-91,2021-03-31,1,BR MALLS PARTICIPACOES S.A.,019909,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-03-31,3.01,Receita de Venda de Bens e/ou Serviços,283760.0000000000,S
28847,06.977.745/0001-91,2021-03-31,1,BR MALLS PARTICIPACOES S.A.,019909,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-03-31,3.01,Receita de Venda de Bens e/ou Serviços,230691.0000000000,S
28848,06.977.745/0001-91,2021-03-31,1,BR MALLS PARTICIPACOES S.A.,019909,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-03-31,3.02,Custo dos Bens e/ou Serviços Vendidos,-32153.0000000000,S
28849,06.977.745/0001-91,2021-03-31,1,BR MALLS PARTICIPACOES S.A.,019909,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-03-31,3.02,Custo dos Bens e/ou Serviços Vendidos,-26611.0000000000,S
28850,06.977.745/0001-91,2021-03-31,1,BR MALLS PARTICIPACOES S.A.,019909,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-03-31,3.03,Resultado Bruto,251607.0000000000,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29177,06.977.745/0001-91,2021-09-30,1,BR MALLS PARTICIPACOES S.A.,019909,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-07-01,2021-09-30,3.99.02,Lucro Diluído por Ação,0.0000000000,N
29178,06.977.745/0001-91,2021-09-30,1,BR MALLS PARTICIPACOES S.A.,019909,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-01-01,2020-09-30,3.99.02.01,ON,0.0000000000,N
29179,06.977.745/0001-91,2021-09-30,1,BR MALLS PARTICIPACOES S.A.,019909,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2020-07-01,2020-09-30,3.99.02.01,ON,0.0000000000,N
29180,06.977.745/0001-91,2021-09-30,1,BR MALLS PARTICIPACOES S.A.,019909,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-09-30,3.99.02.01,ON,0.0000000000,N
29181,06.977.745/0001-91,2021-09-30,1,BR MALLS PARTICIPACOES S.A.,019909,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-07-01,2021-09-30,3.99.02.01,ON,0.0000000000,N

In [ ]:
df.dtypes

CNPJ_CIA         object
DT_REFER         object
VERSAO           object
DENOM_CIA        object
CD_CVM           object
GRUPO_DFP        object
MOEDA            object
ESCALA_MOEDA     object
ORDEM_EXERC      object
DT_INI_EXERC     object
DT_FIM_EXERC     object
CD_CONTA         object
DS_CONTA         object
VL_CONTA         object
ST_CONTA_FIXA    object
dtype: object

# 3. Criação de uma rotina de extração

In [ ]:
df.DT_FIM_EXERC.unique()

array(['2020-03-31', '2021-03-31', '2020-06-30', '2021-06-30',
       '2020-09-30', '2021-09-30', '2020-12-31', '2021-12-31',
       '2020-05-31', '2021-05-31', '2020-08-31', '2021-08-31',
       '2020-11-30', '2021-11-30'], dtype=object)

In [ ]:
df.DT_REFER.unique()

array(['2021-03-31', '2021-06-30', '2021-09-30', '2021-12-31',
       '2021-05-31', '2021-08-31', '2021-11-30'], dtype=object)

### Construindo o Loop

Vamos criar um loop que vai fazer a captura de vários demonstrativos de uma vez, e depois filtrar empresas específicas

Quando isso for terminado, ele vai gerar um excel por empresa, onde cada aba será um demonstrativo diferente

O usuário terá apenas que passar uma lista de empresas que deseja e também uma lista com demonstrativos

In [ ]:
demonstrativos = ['DFC_MD', 'DFC_MI','BPA','DRE']

In [ ]:
empresas

['22357', '22357', '19925', '19925', '20494', '20605', '20982', '20982']

In [ ]:
empresas.append('9512')

In [ ]:
empresas

['22357',
 '22357',
 '19925',
 '19925',
 '20494',
 '20605',
 '20982',
 '20982',
 '9512']

Link para demonstrativos trimestrais: http://dados.cvm.gov.br/dados/CIA_ABERTA/DOC/ITR/DADOS/itr_cia_aberta_2021.zip

Link para demonstrativos anuais: http://dados.cvm.gov.br/dados/CIA_ABERTA/DOC/DFP/DADOS/dfp_cia_aberta_2021.zip

In [ ]:
j = '9512'

'00' + j

'009512'

In [ ]:
j.zfill(6)

'009512'

In [ ]:
import time
start_time = time.time()

import zipfile
import io

lista_listas = []

a = 0

for j in empresas:

  lista_df = []


  for k in demonstrativos:

    link = 'http://dados.cvm.gov.br/dados/CIA_ABERTA/DOC/ITR/DADOS/itr_cia_aberta_2021.zip'

    arquivo_zip = requests.get(link)

    zf = zipfile.ZipFile(io.BytesIO(arquivo_zip.content))

    arquivo = 'itr_cia_aberta_' + str(k) + '_con_2021.csv'

    dados = zf.open(arquivo)

    linhas = dados.readlines()

    lines = [i.strip().decode('ISO-8859-1') for i in linhas]

    lines = [i.split(';') for i in lines]

    df = pd.DataFrame(lines[1:], columns = lines[0])

    df['VL_AJUSTADO'] = pd.to_numeric(df['VL_CONTA'])

    filtro = df[df['CD_CVM']== str(j).zfill(6)]

    lista_df.append(filtro)

    print(f'Trabalhando com a empresa {j} e seu demonstrativo {k}. As dimensões são {filtro.shape} ')

  lista_listas.append(lista_df)

  # Utilizando a biblioteca xlsxwriter
  writer = pd.ExcelWriter(f'Demonstrativos Empresa {str(j)}.xlsx', engine= 'xlsxwriter')

  # Especifique o que esse arquivo de Excel vai conter
  lista_listas[a][0].to_excel(writer, sheet_name = 'DFC_MD')
  lista_listas[a][1].to_excel(writer, sheet_name = 'DFC_MI')
  lista_listas[a][2].to_excel(writer, sheet_name = 'BPA')
  lista_listas[a][3].to_excel(writer, sheet_name = 'DRE')
  #lista_listas[a][4].to_excel(writer, sheet_name = 'BPP', encoding = 'ISO-8859-1')

  a += 1

  print(f'Arquivo Excel com os demonstrativos da empresa {str(j)} já foi exportado. \n')

  # Fechar o arquivo Excel
  writer.close()

print("O tempo de execução desse programa foi de %s segundos ---" %(time.time() -start_time))

Trabalhando com a empresa 22357 e seu demonstrativo DFC_MD. As dimensões são (0, 16)
Trabalhando com a empresa 22357 e seu demonstrativo DFC_MI. As dimensões são (422, 16)
Trabalhando com a empresa 22357 e seu demonstrativo BPA. As dimensões são (372, 15)
Trabalhando com a empresa 22357 e seu demonstrativo DRE. As dimensões são (300, 16)
Arquivo Excel com os demonstrativos da empresa 22357 já foi exportado.

Trabalhando com a empresa 22357 e seu demonstrativo DFC_MD. As dimensões são (0, 16)
Trabalhando com a empresa 22357 e seu demonstrativo DFC_MI. As dimensões são (422, 16)
Trabalhando com a empresa 22357 e seu demonstrativo BPA. As dimensões são (372, 15)
Trabalhando com a empresa 22357 e seu demonstrativo DRE. As dimensões são (300, 16)
Arquivo Excel com os demonstrativos da empresa 22357 já foi exportado.

Trabalhando com a empresa 19925 e seu demonstrativo DFC_MD. As dimensões são (0, 16)
Trabalhando com a empresa 19925 e seu demonstrativo DFC_MI. As dimensões são (386, 16)
Trabalhando com a empresa 19925 e seu demonstrativo BPA. As dimensões são (384, 15)
Trabalhando com a empresa 19925 e seu demonstrativo DRE. As dimensões são (386, 16)
Arquivo Excel com os demonstrativos da empresa 19925 já foi exportado.

Trabalhando com a empresa 19925 e seu demonstrativo DFC_MD. As dimensões são (0, 16)
Trabalhando com a empresa 19925 e seu demonstrativo DFC_MI. As dimensões são (386, 16)
Trabalhando com a empresa 19925 e seu demonstrativo BPA. As dimensões são (384, 15)
Trabalhando com a empresa 19925 e seu demonstrativo DRE. As dimensões são (386, 16)
Arquivo Excel com os demonstrativos da empresa 19925 já foi exportado.

Trabalhando com a empresa 20494 e seu demonstrativo DFC_MD. As dimensões são (0, 16)
Trabalhando com a empresa 20494 e seu demonstrativo DFC_MI. As dimensões são (308, 16)
Trabalhando com a empresa 20494 e seu demonstrativo BPA. As dimensões são (408, 15)
Trabalhando com a empresa 20494 e seu demonstrativo DRE. As dimensões são (300, 16)
Arquivo Excel com os demonstrativos da empresa 20494 já foi exportado.

Trabalhando com a empresa 20605 e seu demonstrativo DFC_MD. As dimensões são (0, 16)
Trabalhando com a empresa 20605 e seu demonstrativo DFC_MI. As dimensões são (274, 16)
Trabalhando com a empresa 20605 e seu demonstrativo BPA. As dimensões são (390, 15)
Trabalhando com a empresa 20605 e seu demonstrativo DRE. As dimensões são (420, 16)
Arquivo Excel com os demonstrativos da empresa 20605 já foi exportado.

Trabalhando com a empresa 20982 e seu demonstrativo DFC_MD. As dimensões são (0, 16)
Trabalhando com a empresa 20982 e seu demonstrativo DFC_MI. As dimensões são (342, 16)
Trabalhando com a empresa 20982 e seu demonstrativo BPA. As dimensões são (378, 15)
Trabalhando com a empresa 20982 e seu demonstrativo DRE. As dimensões são (374, 16)
Arquivo Excel com os demonstrativos da empresa 20982 já foi exportado.

Trabalhando com a empresa 20982 e seu demonstrativo DFC_MD. As dimensões são (0, 16)
Trabalhando com a empresa 20982 e seu demonstrativo DFC_MI. As dimensões são (342, 16)
Trabalhando com a empresa 20982 e seu demonstrativo BPA. As dimensões são (378, 15)
Trabalhando com a empresa 20982 e seu demonstrativo DRE. As dimensões são (374, 16)
Arquivo Excel com os demonstrativos da empresa 20982 já foi exportado.

Trabalhando com a empresa 9512 e seu demonstrativo DFC_MD. As dimensões são (0, 16)
Trabalhando com a empresa 9512 e seu demonstrativo DFC_MI. As dimensões são (374, 16)
Trabalhando com a empresa 9512 e seu demonstrativo BPA. As dimensões são (390, 15)
Trabalhando com a empresa 9512 e seu demonstrativo DRE. As dimensões são (430, 16)
Arquivo Excel com os demonstrativos da empresa 9512 já foi exportado.

O tempo de execução desse programa foi de 356.14886450767517 segundos ---

# 4. Transformando os dados

In [ ]:
pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Downloading openpyxl-3.1.2-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-1.1.0-py3-none-any.whl.metadata (1.8 kB)
Downloading openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
   ---------------------------------------- 0.0/250.0 kB ? eta -:--:--
   - -------------------------------------- 10.2/250.0 kB ? eta -:--:--
   ---- ---------------------------------- 30.7/250.0 kB 330.3 kB/s eta 0:00:01
   ----------- --------------------------- 71.7/250.0 kB 563.7 kB/s eta 0:00:01
   -------------------------------- ------- 204.8/250.0 kB 1.2 MB/s eta 0:00:01
   ---------------------------------------- 250.0/250.0 kB 1.3 MB/s eta 0:00:00
Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.2
Note: you may need to restart the kernel to use updated packages.

In [ ]:
#Importar todas as bibliotecas

import plotly
import investpy
import os
import numpy as np
import pandas as pd
import openpyxl

### Tabela DRE

In [ ]:
#Capturar os arquivos que estão no diretório criado na etapa do webscrapping

caminho = os.getcwd()
arquivos = os.listdir(caminho)
arquivos

['.ipynb_checkpoints',
 'Analise_Fundamentalista.ipynb',
 'Arquivos_Aula',
 'Demonstrativos Empresa 19925.xlsx',
 'Demonstrativos Empresa 20494.xlsx',
 'Demonstrativos Empresa 20605.xlsx',
 'Demonstrativos Empresa 20982.xlsx',
 'Demonstrativos Empresa 22357.xlsx',
 'Demonstrativos Empresa 9512.xlsx',
 'Demonstrativos_Empresa_22357.xlsx',
 'Extração da tabela de DI da B3.ipynb',
 'Mód_3 - Conceitos em Finanças e Macroeconomia..ipynb',
 'Mód_4 - Estatística no Mercado Financeiro.ipynb',
 'Mód_5 - Calculo Mercado Financeiro.ipynb',
 'Mód_6 - Análise_Técnica.ipynb',
 'Mód_7 - Análise Fundamentalista.ipynb',
 'Obtenção de dados de fundos de investimento.ipynb',
 'Taxa_DI.ipynb']

In [ ]:
#Juntamos todos esses xslxs em uma lista

arquivos_xls = [f for f in arquivos if f[-1] == 'x']
arquivos_xls

['Demonstrativos Empresa 19925.xlsx',
 'Demonstrativos Empresa 20494.xlsx',
 'Demonstrativos Empresa 20605.xlsx',
 'Demonstrativos Empresa 20982.xlsx',
 'Demonstrativos Empresa 22357.xlsx',
 'Demonstrativos Empresa 9512.xlsx',
 'Demonstrativos_Empresa_22357.xlsx']

In [ ]:
#Criando o DF
dre = pd.DataFrame()

In [ ]:
#Vamos juntar todos os arquivos xlsx em uma grande tabela DRE

for f in arquivos_xls:
  drexls = pd.read_excel(f, sheet_name='DRE')
  dre = pd.concat([dre, drexls])

ValueError: Excel file format cannot be determined, you must specify an engine manually.